name: Auto Post to Blogger
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install google-generativeai

      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.HF_TOKEN }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python main.py
